linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck # default end
    - bodyclose
    - cyclop
    - errorlint
    - exportloopref
    - goerr113
    - makezero
    - unparam
    - durationcheck
    - errname
    - exhaustive
    - noctx
    - prealloc
    - unparam
    - exportloopref
    - rowserrcheck
    - nestif
    - contextcheck
    - nilnil

linters-settings:
  errorlint:
    errorf: true
    asserts: true
    comparison: true
